export const ICONS_URI = {

    account: require('../assests/icons/account.png'),
    addUser: require('../assests/icons/addUser.png'),
    arrow: require('../assests/icons/arrow.png'),
    bell: require('../assests/icons/bell.png'),
    block: require('../assests/icons/block.png'),
    call: require('../assests/icons/call.png'),
    camera: require('../assests/icons/camera.png'),
    comment: require('../assests/icons/comment.png'),
    notification: require('../assests/icons/notification.png'),
    threeDots: require('../assests/icons/dots.png'),
    group: require('../assests/icons/group.png'),
    bottomGroup: require('../assests/icons/bottomGroup.png'),
    questionMark: require('../assests/icons/help.png'),
    unlike: require('../assests/icons/unlike.png'),
    info: require('../assests/icons/info.png'),
    status: require('../assests/icons/status.png'),
    onlineShow: require('../assests/icons/online.png'),
    pen: require('../assests/icons/pen.png'),
    twoPeoplesGroup: require('../assests/icons/people.png'),
    timer: require('../assests/icons/timer.png'),
    voice: require('../assests/icons/voice.png'),
    send: require('../assests/icons/send.png'),
    sendTick: require('../assests/icons/tick.png'),
    // readMessage: require('../assests/icons/readMessage.png'),
    scanner: require('../assests/icons/scanner.png'),
    search: require('../assests/icons/search.png'),
    uploadProfile: require('../assests/icons/uploadProfile.png'),
    greenCall: require('../assests/icons/greenCall.png'),
    archive: require('../assests/icons/archive.png'),
    delete: require('../assests/icons/delete.png'),
    ChatBack: require('../assests/icons/ChatBack.png'),
    User: require('../assests/icons/user.png'),
    privacy: require('../assests/icons/privacy.png'),
    privateChat: require('../assests/icons/private-chat.png'),
    storageCloud: require('../assests/icons/cloud-computing.png'),
    world: require('../assests/icons/world.png'),
    list: require('../assests/icons/list.png'),
    marker: require('../assests/icons/marker.png'),
    attached: require('../assests/icons/attachFile.png'),
    play: require('../assests/icons/play.png'),
    pause: require('../assests/icons/pause.png'),
    select: require('../assests/icons/select.png'),
    notSelect: require('../assests/icons/notSelect.png'),
    viewStatus: require('../assests/icons/view.png'),

}