export const IMAGES_URI = {
    taqiFollow: require('../assests/Images/taqiFollow.jpg'),
    samaFollow: require('../assests/Images/samaFollow.jpg'),
    ronaldoFollow: require('../assests/Images/ronaldoFollow.jpg'),
    olympicsFollow: require('../assests/Images/olympicsFollow.jpg'),
    markFollow: require('../assests/Images/markFollow.jpg'),
    imranFollow: require('../assests/Images/imranFollow.jpg'),
    geoFollow: require('../assests/Images/geoFollow.jpg'),
    footballFollow: require('../assests/Images/footballFollow.jpg'),
    elonFollow: require('../assests/Images/elonFollow.jpg'),
    ecommerceGroup: require('../assests/Images/ecommerceGroup.jpg'),
    codingGroup: require('../assests/Images/codingGroup.jpg'),
    cnnFollow: require('../assests/Images/cnnFollow.jpg'),
    chatBg: require('../assests/Images/chatBg.jpg'),
    agreeAndContinue: require('../assests/Images/agreeAndContinue.jpg'),
    adamjeeGroup: require('../assests/Images/adamjeeGroup.jpg'),
    background: require('../assests/Images/background.jpg'),
}